### ISSUE TITLE
Feature : Option to remove borders on Mobile.

### ISSUE THREAD

**Issue by WinnerWind** [isaacfreeman/kakano-obsidian-theme#1]
I use quite a lot of themes on Android, and (no offense) I feel that Kakano's theme for Android makes me feel really claustraphobic, as if there is not enough space for me to write what I want, without the sentence wrapping itself over.
Maybe I'm just a nitpicky person, but an option to *change the size* or *remove* the coloured border (using style settings or similar) would really help make this theme more comfortable for those with tall screens.

**Comment by isaacfreeman** [comment]
Thanks @WinnerWind. I don't feel the mobile theme is quite right yet, so that's useful feedback. On one hand I'd like to maintain some visibility of the background color, as it's really a key point of the theme to give some visual distinction to different vaults (I often switch between work and personal vaults, so I want to see at a glance which one I'm in). On the other hand though, I very much take your point that it's important to keep as much horizontal space as possible.

I'll explore this soon and see what I can come up with, either as a setting or just an outright change.

If it's convenient for you, it'd be really valuable to see a screenshot so I can understand your screen size and shape, and also your font size. It would also be great to know what kind of text you're typically writing on mobile: I normally use the mobile app (on iOS) for notes with checklists, and it sounds like you might be writing longer text. That's something I haven't thought much about yet and I can see how it would make a big difference to how much horizontal space is needed.

> Maybe I'm just a nitpicky person

Please continue to be! This is the first piece of feedback I've had on Kakano, and I really appreciate it.

**Comment by isaacfreeman** [comment]
@WinnerWind
I've added a setting for this, hope it works for you.
![IMG_3618](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/342659/e610686f-952b-4f5b-9c6c-309a30f1c5e6)

As a detail, when the side spacing is zero, the corners of the note are no longer rounded.

Thanks for contributing! I've added a Credits section to the README to mention you, linking to your Github account. Let me know if you'd prefer a different URL.

**Comment by WinnerWind** [comment]
Hi there! So sorry I didn't reply sooner. I was travelling.
If possible, can you make the credits link to my GitHub IO page instead? (winnerwind.github.io)
I'll update my theme and check the settings out.

**Comment by isaacfreeman** [comment]
> If possible, can you make the credits link to my GitHub IO page instead?

Done!

**Comment by WinnerWind** [comment]
Hi there!
I just updated Kakano and checked out the new setting!
It really is perfect as far as my eyes can tell!
Still feels like Kakano even though the borders are gone, and feels a lot more spacious too!
Thank you! Cheers.

**Comment by isaacfreeman** [comment]
> Still feels like Kakano even though the borders are gone, and feels a lot more spacious too! 

Glad you like it, and thanks for the screenshots. It's always good to see how people are using the theme, especially on devices I don't have myself.

> Note : It seems that the theme has not recieved an update in all my vaults. It still shows as Version 1.11.0 in some vaults for some unknown reason.

I've noticed that. TL;DR I think it's a bug in the mobile version of Obsidian. It's using the current 2.8.0 theme, but it says in settings that the last supported version is 1.11.0.

Longer version...
The iOS app reports `Version: 1.11.0 (currently installed: 2.8.0)`, whereas the macOS app correctly reports version 2.8.0. I'm pretty sure I know what's going on here: the theme has a `versions.json` file which records which versions of the theme work on which versions of the app.  In there it basically says that if the app version is higher than 1.5.0, the most recent version of Kakano will work. But if you're still on an older version of the app, the last Kakano version that's known to work is 1.11.0. The idea is to protect users from getting a theme version that looks weird if they're not ready to update their app yet.
The problem is that the macOS app (and presumably Windows and Linux) is currently on v1.5.3, but the iOS (and presumably Android) app has a different version number: 1.4.16. So mobile Obsidian seems to be using the current theme fine, but in settings it incorrectly reports the older Kakano version as current.

I'm not aware that there's anything I can do in the theme to correct this, but I'll make a note to check again. I haven't treated it as a high priority, because the current version of Kakano does actually get used on mobile.
