### ISSUE TITLE
Title not showing in notes

### ISSUE THREAD

**Issue by rotie-alt** [isaacfreeman/kakano-obsidian-theme#7]
Couldn't find any setting that would allow showing and editing the title back on the notes

**Comment by isaacfreeman** [comment]
Thanks, good point. This was a choice that worked for me early on when I was the only user of the theme, but needs to change to accommodate different people's working styles. I'm putting it on my list to address soon, and I'll let you know here when there's an update.

**Comment by isaacfreeman** [comment]
Version 2.16.0 is now available, which restores the ability to show inline titles for notes. You may need to force reload after updating.
<img width="704" alt="Screenshot 2024-04-01 at 13 23 00" src="https://github.com/isaacfreeman/kakano-obsidian-theme/assets/342659/5e6c5104-4b29-45df-b764-196166ee9f3b">

I'd be interested to hear your thoughts. My reasoning so far has been along these lines:

1. The inline title is the filename for the note, which might be different from the full title of the note.
2. Users can make a full title with a level 1 heading anywhere in the document, and this is more important than the filename.
3. As it's more important, the level 1 heading has greater visual weight than the filename.It's bigger, and has more visual weight.
4. There are two ways to display the filename at the top of a note: `Show inline title` (which shows just the title), and `Show tab title bar` (which shows title and directory, plus navigation controls).
5. Most users will probably want to use one or other of these options, but having both is redundant.

This makes sense for me, but it also means that I typically use Obsidian with `Show inline title` switched off, because I don't think of it as the "real" title, just the filename. I'm open to other people thinking differently! 

I'll leave this issue open for a while: let me know if it doesn't look right to you.
