### ISSUE TITLE
Window Frame Styling in Kakano (Windows 10)

### ISSUE THREAD

**Issue by WinnerWind** [isaacfreeman/kakano-obsidian-theme#9]
# Obsidian Frame
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/f38dd498-c111-426a-be21-c4502d822ed0)
# Hidden
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/7cea3910-ac12-4ea1-9d90-a878477c367b)
# Native Frame
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/6f27891e-120a-4a13-8c32-991aa9492f15)

As one can see, in the Hidden and Obsidian Frame setting, the Close button's icon is never visible. It turns red once the mouse is hovered over it.
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/f337dd2b-f6e8-4d60-b56d-718de7cb3147)
 
 Note : Kakano v2.17.1

**Comment by WinnerWind** [comment]
That missing closed button has been here for a while, however I really didn't think much of it, thinking it was a feature.
I wish you luck in fixing it :)

**Comment by isaacfreeman** [comment]
I've fixed the close button in the current version. It turned out that on on Windows Obsidian removes the normal window controls entirely and makes its own (macOS doesn't allow this – sensibly in my view). It happened that Obsidian's version of the window close button uses the same CSS class name as other close buttons within the Obsidian UI, so it was picking up parts of my styles for those, including the round shape.

I'll close this issue now with the fixed close button, but there are other things still to fix on Windows. I have a borrowed Windows laptop on my desk now to work on these. Thanks for your help!
